# Generated by Django 3.2.7 on 2021-09-14 10:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
