# Generated by Django 3.2.7 on 2021-09-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_coursemodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_image',
            field=models.ImageField(upload_to='course'),
        ),
    ]
